### ISSUE TITLE
Allow exiting stdout writes on SIGPIPE

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled#25]
Appears this will require replacing `System.out` with `FileDescriptor.out`
```java
try (PrintWriter w = new PrintWriter(new FileWriter(FileDescriptor.out))) { ...
```

and explicit `w.checkError()` when writing.  Checking every write is prohibitively slow
```
$ time java sigpipeTest | wc -l
 20000000

real    0m26.119s
user    0m16.889s
sys     0m26.754s

$ time java sigpipeTest | head | wc -l
      10

real    0m0.145s
user    0m0.090s
sys     0m0.045s
```

vs checking every 10000 writes
```
$ time java sigpipeTest | wc -l
 20000000

real    0m3.266s
user    0m3.434s
sys     0m0.184s

$ time java sigpipeTest | head | wc -l
      10

real    0m0.155s
user    0m0.129s
sys     0m0.046s
```

**Comment by heuermh** [comment]
Yikes, JVM crashes in unit tests
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project dsh-compress: There are test failures.
[ERROR]
[ERROR] Please refer to dishevelled/compress/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd dishevelled/compress && /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/jre/bin/java -jar dishevelled/compress/target/surefire/surefirebooter4233541551378049141.jar dishevelled/compress/target/surefire 2021-11-10T12-58-23_642-jvmRun1 surefire2265215761292242900tmp surefire_06049636221176186699tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.dishevelled.compress.WritersTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd dishevelled/compress && /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/jre/bin/java -jar dishevelled/compress/target/surefire/surefirebooter4233541551378049141.jar dishevelled/compress/target/surefire 2021-11-10T12-58-23_642-jvmRun1 surefire2265215761292242900tmp surefire_06049636221176186699tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.dishevelled.compress.WritersTest
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by heuermh** [comment]
Another approach? https://gist.github.com/kannangce/f6c0a9d43c1632be8e72b55e45044e7a

**Comment by heuermh** [comment]
Closing as WontFix, will use Signal/SignalHandler downstream
